### ISSUE TITLE
Android Mobile forms issue

### ISSUE THREAD

**Issue by stokesdy** [SpartaHack/SpartaHack2016-Website#8] opened 2015-11-05 00:28 UTC
Android 4.3 (Jelly bean) using Chrome browser. When clicking on the drop downs such as birthday, my keyboard is displayed and then instantly closes. The drop down also displays for a split second but also closes.

![screenshot_2015-11-04-19-23-20](https://cloud.githubusercontent.com/assets/8905066/10956498/2eb0e916-832a-11e5-84e1-d74496fdeb6a.png)

**Comment by bogderp** [comment] 2015-11-30 06:54
Duplicate of issue #7

**Closed as completed by bogderp** 2015-11-30 06:54 UTC
